# Evaluator

In [1]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
from stargazer.stargazer import Stargazer

pd.options.display.max_rows = 4000
ev = pd.read_excel('../../interim/01_cleaned/evaluator_main.xlsx')
ev = ev[ev['attention']==0.5].reset_index()

#### Attention

In [2]:
ev['attention'].value_counts()

0.5    44
Name: attention, dtype: int64

In [3]:
ev[['Total approvals', 'Time taken']].describe()

       Total approvals  Time taken
count        44.000000   44.000000
mean        603.977273  475.068182
std         393.488659  187.414278
min           6.000000  185.000000
25%         304.000000  335.000000
50%         580.000000  438.500000
75%         818.250000  561.250000
max        1688.000000  933.000000

#### Difficulty

In [4]:
#calculate weighted average
ev['wa_difficulty'] = np.nan
for i in range(ev.shape[0]):
    wa = 0
    for j in range(11):
        wa += (ev['difficulty' + str(j)][i]/100)*j
    ev.loc[i, 'wa_difficulty'] = wa

In [5]:
ev['wa_difficulty'].describe()

count    44.000000
mean      4.396364
std       1.648241
min       0.250000
25%       3.835000
50%       4.440000
75%       5.117500
max       8.310000
Name: wa_difficulty, dtype: float64

#### Punishment

In [6]:
ev[(ev['punish_del_good']==0) & (ev['punish_del_bad']==0) & (ev['punish_nodel_bad']==0) & (ev['punish_nodel_good']==0)]

,index,Unnamed: 0,participant.id_in_session,participant.code,app,page,session.code,bad_outcome_eva,good_outcome_eva,max_punishment,...,Age,Sex,Ethnicity simplified,Country of birth,Country of residence,Nationality,Language,Student status,Employment status,wa_difficulty
0,1,1,2,mwxkx53p,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,37,Male,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,3.97
1,2,2,3,esiwq5xl,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,58,Female,White,United Kingdom,United Kingdom,United Kingdom,English,No,Part-Time,6.84
2,3,3,7,ytxjvjpt,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,45,Male,White,United Kingdom,United Kingdom,United Kingdom,English,Yes,Part-Time,3.41
3,5,5,10,9dhv5hz4,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,22,Female,Asian,China,United Kingdom,China,Chinese,Yes,Full-Time,4.87
4,6,6,11,ylta0pe0,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,29,Female,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,4.17
6,9,9,15,eex8lgoc,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,42,Male,White,Ireland,United Kingdom,United Kingdom,English,Yes,Full-Time,5.02
9,12,12,18,g63wihfa,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,58,Male,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,0.85
10,14,14,20,aegxr56b,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,48,Male,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,5.50
12,17,17,26,plxurrau,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,47,Female,Mixed,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,4.05
13,18,18,27,w38g73qm,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,36,Female,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,0.62
21,26,26,39,5b8vi6i8,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,48,Female,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,5.11
24,30,30,44,ae21lg02,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,34,Male,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,4.58
27,33,33,47,s6kt6cvy,eva_punish,BackToProlific,k0xblwkb,1,5,2,...,20,Female,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,4.40
32,39,39,3,bcd1lw3l,eva_punish,BackToProlific,joqllgqx,1,5,2,...,25,Female,Other,United Kingdom,United Kingdom,United Kingdom,English,Yes,Full-Time,6.03
35,42,42,8,2rfkxj5k,eva_punish,BackToProlific,joqllgqx,1,5,2,...,25,Male,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,5.93
36,43,43,10,n7tdjtby,eva_punish,BackToProlific,joqllgqx,1,5,2,...,43,Female,White,United Kingdom,United Kingdom,United Kingdom,English,No,Part-Time,4.17
37,44,44,11,hz0b9cur,eva_punish,BackToProlific,joqllgqx,1,5,2,...,54,Male,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,3.86
43,51,51,2,hfw2zkg7,eva_punish,BackToProlific,g5ucb17o,1,5,2,...,31,Female,White,United Kingdom,United Kingdom,United Kingdom,English,No,Full-Time,4.30

In [7]:
ev[[not i for i in ((ev['punish_del_good']==0) & (ev['punish_del_bad']==0) & (ev['punish_nodel_bad']==0) & (ev['punish_nodel_good']==0))]][['punish_del_good', 'punish_del_bad', 'punish_nodel_good', 'punish_nodel_bad']].describe()

       punish_del_good  punish_del_bad  punish_nodel_good  punish_nodel_bad
count        26.000000       26.000000          26.000000         26.000000
mean          0.553846        0.911538           0.476923          0.940385
std           0.649449        0.685319           0.615992          0.666936
min           0.000000        0.000000           0.000000          0.100000
25%           0.000000        0.250000           0.000000          0.500000
50%           0.325000        1.000000           0.150000          1.000000
75%           1.000000        1.200000           1.000000          1.037500
max           2.000000        2.000000           2.000000          2.000000

In [8]:
ev[['punish_del_good', 'punish_del_bad', 'punish_nodel_good', 'punish_nodel_bad']].describe()

       punish_del_good  punish_del_bad  punish_nodel_good  punish_nodel_bad
count        44.000000       44.000000          44.000000         44.000000
mean          0.327273        0.538636           0.281818          0.555682
std           0.566656        0.691801           0.526185          0.690906
min           0.000000        0.000000           0.000000          0.000000
25%           0.000000        0.000000           0.000000          0.000000
50%           0.000000        0.150000           0.000000          0.225000
75%           0.487500        1.000000           0.262500          1.000000
max           2.000000        2.000000           2.000000          2.000000

In [9]:
ev['bad_good_del'] = ev['punish_del_bad'] - ev['punish_del_good']
ev['bad_good_nodel'] = ev['punish_nodel_bad'] - ev['punish_nodel_good']
ev['nodel_del_good'] = ev['punish_nodel_good'] - ev['punish_del_good']
ev['nodel_del_bad'] = ev['punish_nodel_bad'] - ev['punish_del_bad']

In [10]:
ev[['bad_good_del', 'bad_good_nodel', 'nodel_del_good', 'nodel_del_bad']].describe()

       bad_good_del  bad_good_nodel  nodel_del_good  nodel_del_bad
count     44.000000       44.000000       44.000000      44.000000
mean       0.211364        0.273864       -0.045455       0.017045
std        0.582383        0.631396        0.436399       0.264782
min       -1.800000       -1.000000       -1.450000      -0.500000
25%        0.000000        0.000000        0.000000       0.000000
50%        0.000000        0.000000        0.000000       0.000000
75%        0.400000        0.562500        0.000000       0.000000
max        2.000000        2.000000        2.000000       1.000000

In [47]:
ev_3 = pd.DataFrame(np.repeat(ev.values, 3, axis=0), columns=ev.columns)

#ev delete never punish
ev_p = ev[[not i for i in ((ev['punish_del_good']==0) & (ev['punish_del_bad']==0) & (ev['punish_nodel_bad']==0) & (ev['punish_nodel_good']==0))]]
ev_p_3 = pd.DataFrame(np.repeat(ev_p.values, 3, axis=0), columns=ev_p.columns)

In [52]:
import scipy
print(scipy.stats.mannwhitneyu(ev_3['punish_del_bad'].astype(float), ev_3['punish_nodel_bad'].astype(float)))
print(scipy.stats.mannwhitneyu(ev_p['punish_del_bad'].astype(float), ev_p['punish_nodel_bad'].astype(float)))
print(scipy.stats.mannwhitneyu(ev_p_3['punish_del_bad'].astype(float), ev_p_3['punish_nodel_bad'].astype(float)))

print(scipy.stats.mannwhitneyu(ev_3['punish_del_good'].astype(float), ev_3['punish_nodel_good'].astype(float)))
print(scipy.stats.mannwhitneyu(ev_p['punish_del_good'].astype(float), ev_p['punish_nodel_good'].astype(float)))
print(scipy.stats.mannwhitneyu(ev_p_3['punish_del_good'].astype(float), ev_p_3['punish_nodel_good'].astype(float)))

print(scipy.stats.ttest_ind(ev_3['punish_del_bad'].astype(float), ev_3['punish_nodel_bad'].astype(float)))
print(scipy.stats.ttest_ind(ev_p['punish_del_bad'].astype(float), ev_p['punish_nodel_bad'].astype(float)))
print(scipy.stats.ttest_ind(ev_p_3['punish_del_bad'].astype(float), ev_p_3['punish_nodel_bad'].astype(float)))

print(scipy.stats.ttest_ind(ev_3['punish_del_good'].astype(float), ev_3['punish_nodel_good'].astype(float)))
print(scipy.stats.ttest_ind(ev_p['punish_del_good'].astype(float), ev_p['punish_nodel_good'].astype(float)))
print(scipy.stats.ttest_ind(ev_p_3['punish_del_good'].astype(float), ev_p_3['punish_nodel_good'].astype(float)))

MannwhitneyuResult(statistic=2137.5, pvalue=0.25909547108089104)
MannwhitneyuResult(statistic=62.5, pvalue=0.2658411724256572)
MannwhitneyuResult(statistic=562.5, pvalue=0.04624699829740829)
MannwhitneyuResult(statistic=2259.0, pvalue=0.5158316366054807)
MannwhitneyuResult(statistic=76.0, pvalue=0.6591251682239696)
MannwhitneyuResult(statistic=684.0, pvalue=0.4138290371881497)
Ttest_indResult(statistic=-1.5706112484105559, pvalue=0.11859665575182213)
Ttest_indResult(statistic=-1.1347362854769125, pvalue=0.2676923989769883)
Ttest_indResult(statistic=-2.0192780192427247, pvalue=0.04698476737760752)
Ttest_indResult(statistic=-0.7629007075376262, pvalue=0.4468438724380188)
Ttest_indResult(statistic=-0.47488052736591035, pvalue=0.6391651091648061)
Ttest_indResult(statistic=-0.8450560918419535, pvalue=0.40073205081390195)

In [23]:
ev[['wa_difficulty', 'bad_good_del', 'bad_good_nodel', 'nodel_del_good', 'nodel_del_bad']].corr()

,wa_difficulty,bad_good_del,bad_good_nodel,nodel_del_good,nodel_del_bad
wa_difficulty,1.000000,-0.012699,0.038365,0.086834,0.262531
bad_good_del,-0.012699,1.000000,0.811459,0.103649,-0.093657
bad_good_nodel,0.038365,0.811459,1.000000,-0.378729,-0.024399
nodel_del_good,0.086834,0.103649,-0.378729,1.000000,0.517057
nodel_del_bad,0.262531,-0.093657,-0.024399,0.517057,1.000000

In [24]:
ev['switching_point'].value_counts().sort_index()

0       2
40      1
50      9
60      7
70      9
80      6
90      4
100     2
9999    4
Name: switching_point, dtype: int64

In [28]:
ev.columns

Index(['index', 'Unnamed: 0', 'participant.id_in_session', 'participant.code',
       'app', 'page', 'session.code', 'bad_outcome_eva', 'good_outcome_eva',
       'max_punishment', 'punishment_cost', 'belief_payment_difficulty',
       'risk_payment', 'margin_of_error', 'eva.id_in_group', 'difficulty0',
       'difficulty1', 'difficulty2', 'difficulty3', 'difficulty4',
       'difficulty5', 'difficulty6', 'difficulty7', 'difficulty8',
       'difficulty9', 'difficulty10', 'error_difficulty', 'punish_del_good',
       'punish_del_bad', 'punish_nodel_good', 'punish_nodel_bad', 'attention',
       'switching_point', 'random_risk_prob_pick', 'risk_task_payoff',
       'research_about', 'unclear', 'why_punish_good', 'why_punish_bad',
       'perception', 'trust', 'responsibility', 'accountability', 'p_id',
       'matched_delegator_id', 'match_outcome', 'match_delegation',
       'task_payoff', 'rand_belief', 'belief_difficulty_payoff',
       'punish_payoff', 'risk_task_payoff_20', 'final_payoff', 'bonus_payoff',
       'Time taken', 'Total approvals', 'Ethnicity', 'Living abroad',
       'Fluent languages', 'Technology use at work', 'Employment-sector',
       'Leadership/position of power/supervisory duties',
       'Management experience', 'Highest education level completed',
       'Body weight', 'Religious affiliation', 'Dating apps',
       'Hobbies - categories', 'Weekly device usage',
       'Internet enabled products', 'Assistive technology',
       'Computer programming', 'Socioeconomic status', 'Nft experience',
       'Cryptocurrency', 'Personal income (gbp)', 'Age', 'Sex',
       'Ethnicity simplified', 'Country of birth', 'Country of residence',
       'Nationality', 'Language', 'Student status', 'Employment status',
       'wa_difficulty', 'bad_good_del', 'bad_good_nodel', 'nodel_del_good',
       'nodel_del_bad'],
      dtype='object')

In [34]:
for i in range(ev.shape[0]):
    print(ev[['punish_del_good', 'punish_del_bad', 'punish_nodel_good', 'punish_nodel_bad']].loc[i])
    print(ev[['why_punish_good']].loc[i])
    print(ev[['why_punish_bad']].loc[i])

punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 0, dtype: float64
why_punish_good    NaN
Name: 0, dtype: object
why_punish_bad   NaN
Name: 0, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 1, dtype: float64
why_punish_good    NaN
Name: 1, dtype: object
why_punish_bad   NaN
Name: 1, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 2, dtype: float64
why_punish_good    NaN
Name: 2, dtype: object
why_punish_bad   NaN
Name: 2, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 3, dtype: float64
why_punish_good    NaN
Name: 3, dtype: object
why_punish_bad   NaN
Name: 3, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 4, dtype: float64
why_punish_good    NaN
Name: 4, dtype: object
why_punish_bad   NaN
Name: 4, dtype: float64
punish_del_good      0.00
punish_del_bad       0.25
punish_nodel_good    0.00
punish_nodel_bad     0.20
Name: 5, dtype: float64
why_punish_good    NaN
Name: 5, dtype: object
why_punish_bad   NaN
Name: 5, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 6, dtype: float64
why_punish_good    NaN
Name: 6, dtype: object
why_punish_bad   NaN
Name: 6, dtype: float64
punish_del_good      0.00
punish_del_bad       1.25
punish_nodel_good    0.00
punish_nodel_bad     1.00
Name: 7, dtype: float64
why_punish_good    NaN
Name: 7, dtype: object
why_punish_bad   NaN
Name: 7, dtype: float64
punish_del_good      0.10
punish_del_bad       0.50
punish_nodel_good    0.05
punish_nodel_bad     0.60
Name: 8, dtype: float64
why_punish_good    I am not sure,it felt like I should at least a...
Name: 8, dtype: object
why_punish_bad   NaN
Name: 8, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 9, dtype: float64
why_punish_good    NaN
Name: 9, dtype: object
why_punish_bad   NaN
Name: 9, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 10, dtype: float64
why_punish_good    NaN
Name: 10, dtype: object
why_punish_bad   NaN
Name: 10, dtype: float64
punish_del_good      0.65
punish_del_bad       1.05
punish_nodel_good    0.10
punish_nodel_bad     1.00
Name: 11, dtype: float64
why_punish_good    to gain more
Name: 11, dtype: object
why_punish_bad   NaN
Name: 11, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 12, dtype: float64
why_punish_good    NaN
Name: 12, dtype: object
why_punish_bad   NaN
Name: 12, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 13, dtype: float64
why_punish_good    NaN
Name: 13, dtype: object
why_punish_bad   NaN
Name: 13, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    2.0
punish_nodel_bad     1.0
Name: 14, dtype: float64
why_punish_good    as we are playing in one team, we take a risk ...
Name: 14, dtype: object
why_punish_bad   NaN
Name: 14, dtype: float64
punish_del_good      1.75
punish_del_bad       1.50
punish_nodel_good    0.30
punish_nodel_bad     1.00
Name: 15, dtype: float64
why_punish_good    If they made their own decision and got it rig...
Name: 15, dtype: object
why_punish_bad   NaN
Name: 15, dtype: float64
punish_del_good      2.0
punish_del_bad       2.0
punish_nodel_good    2.0
punish_nodel_bad     2.0
Name: 16, dtype: float64
why_punish_good    I didn't trust them to be correct and thought ...
Name: 16, dtype: object
why_punish_bad   NaN
Name: 16, dtype: float64
punish_del_good      0.45
punish_del_bad       0.35
punish_nodel_good    0.25
punish_nodel_bad     0.25
Name: 17, dtype: float64
why_punish_good    Fairness
Name: 17, dtype: object
why_punish_bad   NaN
Name: 17, dtype: float64
punish_del_good      0.0
punish_del_bad       0.1
punish_nodel_good    0.0
punish_nodel_bad     0.1
Name: 18, dtype: float64
why_punish_good    NaN
Name: 18, dtype: object
why_punish_bad   NaN
Name: 18, dtype: float64
punish_del_good      0.60
punish_del_bad       0.25
punish_nodel_good    0.75
punish_nodel_bad     0.50
Name: 19, dtype: float64
why_punish_good    because it works out better and can earn more
Name: 19, dtype: object
why_punish_bad   NaN
Name: 19, dtype: float64
punish_del_good      0.0
punish_del_bad       2.0
punish_nodel_good    0.0
punish_nodel_bad     2.0
Name: 20, dtype: float64
why_punish_good    NaN
Name: 20, dtype: object
why_punish_bad   NaN
Name: 20, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 21, dtype: float64
why_punish_good    NaN
Name: 21, dtype: object
why_punish_bad   NaN
Name: 21, dtype: float64
punish_del_good      0.0
punish_del_bad       1.0
punish_nodel_good    0.0
punish_nodel_bad     0.5
Name: 22, dtype: float64
why_punish_good    NaN
Name: 22, dtype: object
why_punish_bad   NaN
Name: 22, dtype: float64
punish_del_good      1.0
punish_del_bad       2.0
punish_nodel_good    0.0
punish_nodel_bad     2.0
Name: 23, dtype: float64
why_punish_good    Felt like they didn't deserve it if they used ...
Name: 23, dtype: object
why_punish_bad   NaN
Name: 23, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 24, dtype: float64
why_punish_good    NaN
Name: 24, dtype: object
why_punish_bad   NaN
Name: 24, dtype: float64
punish_del_good      0.45
punish_del_bad       0.25
punish_nodel_good    0.45
punish_nodel_bad     0.25
Name: 25, dtype: float64
why_punish_good    Because I am greedy
Name: 25, dtype: object
why_punish_bad   NaN
Name: 25, dtype: float64
punish_del_good      2.0
punish_del_bad       0.2
punish_nodel_good    1.1
punish_nodel_bad     0.5
Name: 26, dtype: float64
why_punish_good    I thought about whether they referred to an al...
Name: 26, dtype: object
why_punish_bad   NaN
Name: 26, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 27, dtype: float64
why_punish_good    NaN
Name: 27, dtype: object
why_punish_bad   NaN
Name: 27, dtype: float64
punish_del_good      1.0
punish_del_bad       1.0
punish_nodel_good    1.0
punish_nodel_bad     1.0
Name: 28, dtype: float64
why_punish_good    I thought it fair
Name: 28, dtype: object
why_punish_bad   NaN
Name: 28, dtype: float64
punish_del_good      1.0
punish_del_bad       1.0
punish_nodel_good    1.0
punish_nodel_bad     0.5
Name: 29, dtype: float64
why_punish_good    LUCK
Name: 29, dtype: object
why_punish_bad   NaN
Name: 29, dtype: float64
punish_del_good      1.0
punish_del_bad       1.0
punish_nodel_good    1.0
punish_nodel_bad     1.0
Name: 30, dtype: float64
why_punish_good    as im a student so money is tight so the more ...
Name: 30, dtype: object
why_punish_bad   NaN
Name: 30, dtype: float64
punish_del_good      0.00
punish_del_bad       0.00
punish_nodel_good    0.00
punish_nodel_bad     0.15
Name: 31, dtype: float64
why_punish_good    NaN
Name: 31, dtype: object
why_punish_bad   NaN
Name: 31, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 32, dtype: float64
why_punish_good    NaN
Name: 32, dtype: object
why_punish_bad   NaN
Name: 32, dtype: float64
punish_del_good      0.0
punish_del_bad       0.1
punish_nodel_good    0.0
punish_nodel_bad     0.1
Name: 33, dtype: float64
why_punish_good    NaN
Name: 33, dtype: object
why_punish_bad   NaN
Name: 33, dtype: float64
punish_del_good      0.1
punish_del_bad       1.0
punish_nodel_good    0.1
punish_nodel_bad     2.0
Name: 34, dtype: float64
why_punish_good    only a little to prove i was looking
Name: 34, dtype: object
why_punish_bad   NaN
Name: 34, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 35, dtype: float64
why_punish_good    NaN
Name: 35, dtype: object
why_punish_bad   NaN
Name: 35, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 36, dtype: float64
why_punish_good    NaN
Name: 36, dtype: object
why_punish_bad   NaN
Name: 36, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 37, dtype: float64
why_punish_good    NaN
Name: 37, dtype: object
why_punish_bad   NaN
Name: 37, dtype: float64
punish_del_good      1.0
punish_del_bad       2.0
punish_nodel_good    1.0
punish_nodel_bad     2.0
Name: 38, dtype: float64
why_punish_good    The way in which the conclusion was arrived at.
Name: 38, dtype: object
why_punish_bad   NaN
Name: 38, dtype: float64
punish_del_good      0.0
punish_del_bad       1.0
punish_nodel_good    0.0
punish_nodel_bad     1.0
Name: 39, dtype: float64
why_punish_good    NaN
Name: 39, dtype: object
why_punish_bad   NaN
Name: 39, dtype: float64
punish_del_good      1.10
punish_del_bad       2.00
punish_nodel_good    1.10
punish_nodel_bad     1.95
Name: 40, dtype: float64
why_punish_good    because I want to win as much as possible and ...
Name: 40, dtype: object
why_punish_bad   NaN
Name: 40, dtype: float64
punish_del_good      0.2
punish_del_bad       0.9
punish_nodel_good    0.2
punish_nodel_bad     0.8
Name: 41, dtype: float64
why_punish_good    It wouldn't let me move on unless I made it hi...
Name: 41, dtype: object
why_punish_bad   NaN
Name: 41, dtype: float64
punish_del_good      0.00
punish_del_bad       1.00
punish_nodel_good    0.00
punish_nodel_bad     1.05
Name: 42, dtype: float64
why_punish_good    NaN
Name: 42, dtype: object
why_punish_bad   NaN
Name: 42, dtype: float64
punish_del_good      0.0
punish_del_bad       0.0
punish_nodel_good    0.0
punish_nodel_bad     0.0
Name: 43, dtype: float64
why_punish_good    NaN
Name: 43, dtype: object
why_punish_bad   NaN
Name: 43, dtype: float64

In [37]:
ev[['why_punish_good']].loc[8]

why_punish_good    I am not sure,it felt like I should at least a...
Name: 8, dtype: object

In [28]:
r = [print(i) for i in ev['unclear']]

no
nan
No
No
No
No
No
I'm in the UK where we use the metric system so I had no idea what 10lbs equated to and therefore wasn't sure how difficult it might be to guess within a 10lb range. I did google to convert it into kg at the beginning though. It might be useful to provide metric and imperial together in future
No
no
No
No.
Some of the wording wasn't the clearest and took a couple of times to read and understand.
nan
No
no.
No
nan
not really sure i understood the experiment
No
No it was all clear thank you :)
no
No
nothing unclear
nan
No
No

In [30]:
r = [print(i) for i in ev['why_punish']]

nan
nan
nan
nan
nan
nan
nan
nan
nan
I think it is correct to delegate, as it puts the choice onto an algorithm that gets it right as much as they already did.
nan
nan
nan
nan
Because the partner got the answer wrong.
I didn't because that is not helpful to me.
If they reduced my chances in getting a higher pay out then it's only fair to reduce theirs
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [32]:
r = [print(i) for i in ev['why_punish_del_less']]

nan
nan
nan
nan
nan
nan
nan
nan
nan
They cannot help how well they did previously.
nan
nan
nan
nan
It is unfortunate, but because the partner got it worng and therefore we deserve to suffer the loss together
I would rather get a guaranteed return.
As above - only fair if I lose out that they lose out too
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [26]:
ev['Total approvals'].describe()

count      44.000000
mean      603.977273
std       393.488659
min         6.000000
25%       304.000000
50%       580.000000
75%       818.250000
max      1688.000000
Name: Total approvals, dtype: float64

In [27]:
ev['Time taken'].describe()

count     44.000000
mean     475.068182
std      187.414278
min      185.000000
25%      335.000000
50%      438.500000
75%      561.250000
max      933.000000
Name: Time taken, dtype: float64

In [25]:
ev[['Total approvals', 'Time taken']].corr()

                 Total approvals  Time taken
Total approvals         1.000000    0.120108
Time taken              0.120108    1.000000

In [3]:
ev.columns

Index(['Unnamed: 0', 'participant.id_in_session', 'participant.code', 'app',
       'page', 'session.code', 'bad_outcome_eva', 'good_outcome_eva',
       'max_punishment', 'punishment_cost', 'belief_payment_difficulty',
       'risk_payment', 'margin_of_error', 'eva.id_in_group', 'difficulty0',
       'difficulty1', 'difficulty2', 'difficulty3', 'difficulty4',
       'difficulty5', 'difficulty6', 'difficulty7', 'difficulty8',
       'difficulty9', 'difficulty10', 'error_difficulty', 'punish_del_good',
       'punish_del_bad', 'punish_nodel_good', 'punish_nodel_bad',
       'switching_point', 'random_risk_prob_pick', 'risk_task_payoff',
       'research_about', 'unclear', 'why_punish', 'why_punish_del_less',
       'p_id', 'matched_delegator_id', 'match_outcome', 'match_delegation',
       'attention', 'task_payoff', 'rand_belief', 'belief_difficulty_payoff',
       'punish_payoff', 'final_payoff', 'bonus_payoff', 'Time taken',
       'Total approvals', 'Ethnicity', 'Gender identity', 'Living abroad',
       'Fluent languages', 'Technology use at work', 'Employment-sector',
       'Leadership/position of power/supervisory duties',
       'Management experience', 'Highest education level completed',
       'Body weight', 'Religious affiliation', 'Dating apps',
       'Hobbies - categories', 'Weekly device usage',
       'Internet enabled products', 'Assistive technology',
       'Computer programming', 'Socioeconomic status', 'Nft experience',
       'Cryptocurrency', 'Personal income (gbp)', 'Age', 'Sex',
       'Ethnicity simplified', 'Country of birth', 'Country of residence',
       'Nationality', 'Language', 'Student status', 'Employment status'],
      dtype='object')